// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sysfetdwfkxnhntwgjvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5c2ZldGR3Zmt4bmhudHdnanZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1Njc3MzEsImV4cCI6MjA2NTE0MzczMX0.iEaytHSsuwiSqc4YHoU1xdJAwNig-Le57W0JUPQkdBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);